/******************************************************************************/
/***               Generated by IBExpert 20/08/2021 19:48:31                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_TB_PESSOA_ID;

CREATE TABLE TB_PESSOA (
    PES_ID                 INTEGER NOT NULL,
    PES_RAZAOSOCIAL        VARCHAR(100),
    PES_FANTASIA           VARCHAR(30),
    PES_ATIVOINATIVO       VARCHAR(1) DEFAULT 'V',
    PES_CPFCNPJ            VARCHAR(50),
    PES_RGINSCR            VARCHAR(50),
    PES_FISICAJURIDICA     VARCHAR(1) DEFAULT 'J',
    PES_DTNASCIMENTO       TIMESTAMP,
    PES_DTCADASTRO         TIMESTAMP,
    PES_SITE               VARCHAR(200),
    PES_USUARIO_CAD        VARCHAR(30),
    PES_TELEFONE           VARCHAR(20),
    PES_CELULAR            VARCHAR(20),
    PES_EMAIL              VARCHAR(100),
    PES_COND_PAGTO_PADRAO  INTEGER,
    PES_LIMITE_CREDITO     NUMERIC(18,2),
    PES_DTALTERACAO        TIMESTAMP,
    PES_DTSINCRONISMO      TIMESTAMP,
    GUID_CONTROLE          VARCHAR(50)
);




/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE TB_PESSOA ADD UNIQUE (PES_ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TB_PESSOA_BI */
CREATE OR ALTER TRIGGER TB_PESSOA_BI FOR TB_PESSOA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF ((NEW.PES_ID IS NULL) OR (NEW.PES_ID < 0)) THEN
    NEW.PES_ID = GEN_ID(GEN_TB_PESSOA_ID,1);
END
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
